#!/bin/sh
# ytimg - youtube thumbnail downloader

# Copyright (c) 2021 Zuyoutoki (zuyoutoki at oki dot moe)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# The Software shall be used for Good, not Evil.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
# THE SOFTWARE. 

VID=$(echo $1|sed -En 's/.*(youtu\.be\/|youtube\.com\/.*v=)([a-zA-Z0-9_]+).*/\2/p')
if [ -z "$VID" ]
then
  echo "usage: $0 <link>"
  exit
fi
echo "Video ID: $VID"
echo "Fetching thumbnail URL..."
URL=$(curl "$1" --location --silent --output - | sed -En 's/.*<link rel="image_src" href="(.+)"><meta property="og:site_name".*/\1/p')
if [ -z "$URL" ]
then
  echo "Couldn't find the thumbnail URL."
  exit
fi
echo "Downloading thumbnail..."
curl "$URL" --output "$VID.${URL##*.}" --silent
echo "Done! Thumbnail saved as '$VID.${URL##*.}'"

